### ISSUE TITLE
安装之后无法进入后台

### ISSUE THREAD

**Issue by a13782425** [wuzheng228/hexo-pro#11]
使用npm install --save hexo-pro进行安装后
在浏览器中输入：http://地址/pro 后提示Cannot GET /pro

**Comment by wuzheng228** [comment]
> 使用npm install --save hexo-pro进行安装后 在浏览器中输入：[http://地址/pro](http://%E5%9C%B0%E5%9D%80/pro) 后提示Cannot GET /pro

1.确保你开启了hexo server
2.如果开启了hexo server 后安装完成hexo-pro需要，重启hexo server确保hexo重新加载hexo-pro插件
3.确认_config.yml hexo-pro的配置正确

你可以尝试重启hexo server
