### ISSUE TITLE
求回复：图片无法加载

### ISSUE THREAD

**Issue by kingpluginser** [wuzheng228/hexo-pro#22]
![image](https://github.com/wuzheng228/hexo-pro/assets/116493602/c55074a0-62ed-425c-8c96-2e55e0ad253a)
显示成功图片无法加载，同时用户头像也无法加载，copilot的可能错误排查完毕
![image](https://github.com/wuzheng228/hexo-pro/assets/116493602/86febf55-a42f-45c3-8ea5-3e49c36682f6)

**Comment by wuzheng228** [comment]
这里可能有点bug，1个是太大的图片上传不了，如果正常上传了，你将图片链接剪切下来再黏贴，或者给图片链接换一行应该就显示了，我想想优化一下

**Comment by wuzheng228** [comment]
好像是png后面多了个斜杠，可能这里代码有bug

**Comment by wuzheng228** [comment]
> ![image](https://private-user-images.githubusercontent.com/116493602/312863586-c55074a0-62ed-425c-8c96-2e55e0ad253a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjQyNzUsIm5iZiI6MTcxMDQ2Mzk3NSwicGF0aCI6Ii8xMTY0OTM2MDIvMzEyODYzNTg2LWM1NTA3NGEwLTYyZWQtNDI1Yy04Yzk2LTJlNTVlMGFkMjUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMDUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2NmMmY3ZTA1YTE2NzViODI5MzY2MjVmN2VmYzQwNWQyNzM5OGRmZTdmN2FjNWM0N2UyOTU1NTM4NDdhNGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.weiXzdWnybv53OJXDOpojZDgv0lWHEhv-_PNlJ6Iheo) 显示成功图片无法加载，同时用户头像也无法加载，copilot的可能错误排查完毕 ![image](https://private-user-images.githubusercontent.com/116493602/312864506-86febf55-a42f-45c3-8ea5-3e49c36682f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjQyNzUsIm5iZiI6MTcxMDQ2Mzk3NSwicGF0aCI6Ii8xMTY0OTM2MDIvMzEyODY0NTA2LTg2ZmViZjU1LWE0MmYtNDVjMy04ZWE1LTNlNDljMzY2ODJmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMDUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDM3MjJlOGNiMDNmMTZjOTRmYTkwNGIyYWE3MDVlNmM4NTQ5NDVjYWI0MTA5NDMxYjE0Y2M2OTAwMjUyYmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1TGMEk_e1aJhwPB2_rB8POnkw5PpFq_2Sw_EVrND1xs)

我晚上下班回来修吧，修好通知你，我昨天看到你提的issue了，但是太晚了，感谢你给我star

**Comment by kingpluginser** [comment]
> 好像是png后面多了个斜杠，可能这里代码有bug

谢谢您的回答，不过我今晚在查了网上的错误解决办法，发现了目前可行的解决办法

![Uploading 屏幕截图 2024-03-15 164013.png…]()

**Comment by kingpluginser** [comment]
![image](https://github.com/wuzheng228/hexo-pro/assets/116493602/04aa582c-17fd-4fc6-af48-6359cc5a0dd3)
作者大大，好像.jpg与.png等图片后缀无法使用

**Comment by wuzheng228** [comment]
你把链接贴出来我试试，有一些外部网站的图片肯能会有防止盗链处理的，一般个人博客图片可以自己搭图床，或者用免费图床，免费的可能不稳定，上传图片到图床可以用picgo

**Comment by wuzheng228** [comment]
> ![image](https://private-user-images.githubusercontent.com/116493602/313151497-04aa582c-17fd-4fc6-af48-6359cc5a0dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2NTYsIm5iZiI6MTcxMDU1NDM1NiwicGF0aCI6Ii8xMTY0OTM2MDIvMzEzMTUxNDk3LTA0YWE1ODJjLTE3ZmQtNGZjNi1hZjQ4LTYzNTljYzVhMGRkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwMTU5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWYwYThhNzIxODgzM2YzNmQyZTY1ODVmODg1NzIxYTVjMzExNzY0NjJjOWQ5NjFkYjY2YmI0MDJkMTA5ZWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9_PARSe-3JScS4euWWhO4sozbynwHMxnOudCEZw7k4) 作者大大，好像.jpg与.png等图片后缀无法使用

你把链接贴出来我试试，有一些外部网站的图片肯能会有防止盗链处理的，一般个人博客图片可以自己搭图床，或者用免费图床，免费的可能不稳定，上传图片到图床可以用picgo

**Comment by kingpluginser** [comment]
> > ![image](https://private-user-images.githubusercontent.com/116493602/313151497-04aa582c-17fd-4fc6-af48-6359cc5a0dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NTQ2NTYsIm5iZiI6MTcxMDU1NDM1NiwicGF0aCI6Ii8xMTY0OTM2MDIvMzEzMTUxNDk3LTA0YWE1ODJjLTE3ZmQtNGZjNi1hZjQ4LTYzNTljYzVhMGRkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwMTU5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWYwYThhNzIxODgzM2YzNmQyZTY1ODVmODg1NzIxYTVjMzExNzY0NjJjOWQ5NjFkYjY2YmI0MDJkMTA5ZWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9_PARSe-3JScS4euWWhO4sozbynwHMxnOudCEZw7k4) 作者大大，好像.jpg与.png等图片后缀无法使用
> 
> 你把链接贴出来我试试，有一些外部网站的图片肯能会有防止盗链处理的，一般个人博客图片可以自己搭图床，或者用免费图床，免费的可能不稳定，上传图片到图床可以用picgo

https://img2024.cnblogs.com/blog/1334952/202403/1334952-20240308211650351-803736940.png
https://cn.bing.com//th?id=OHR.AnzaBorregoBloom_ZH-CN8284458835_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp
https://c-ssl.duitang.com/uploads/blog/202211/26/20221126191650_c5637.jpg

**Comment by kingpluginser** [comment]
作者大大我又试了一下情况如下：
![屏幕截图 2024-03-16 121637](https://github.com/wuzheng228/hexo-pro/assets/116493602/2aba81cc-9823-4162-837f-8386c505a745)
图片地址在html语法中可以，而bing壁纸则都可以

**Comment by kingpluginser** [comment]
> 作者大大我又试了一下情况如下： ![屏幕截图 2024-03-16 121637](https://private-user-images.githubusercontent.com/116493602/313373628-2aba81cc-9823-4162-837f-8386c505a745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NjMyNjAsIm5iZiI6MTcxMDU2Mjk2MCwicGF0aCI6Ii8xMTY0OTM2MDIvMzEzMzczNjI4LTJhYmE4MWNjLTk4MjMtNDE2Mi04MzdmLTgzODZjNTA1YTc0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNDIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTNiMGI3ZmQ3NDlhZWIyNjM0YTRjNDE3ZDc2YTQ3OTg5OTM5NDVmNjVmMDcyYzI1ZTFlOGJiODQyMzFkNmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3lk4GizNA7zecDBpAW8xDD_jX1O8kSKT0hK4frKIn7M) 图片地址在html语法中可以，而bing壁纸则都可以

头像就只有bing壁纸的url可以显示

**Comment by kingpluginser** [comment]
项目作者您好，上了床图都可以显示了，麻烦您了
