### ISSUE TITLE
无法渲染数学公式

### ISSUE THREAD

**Issue by iYnOtUo** [wuzheng228/hexo-pro#27]
平常使用没有问题，但是希望增加渲染 latex 公式的功能。
![Screenshot_2024-07-28-01-38-58-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4ad162e9-325b-42a9-8c24-1e2b2025d59c)

**Comment by wuzheng228** [comment]
> 平常使用没有问题，但是希望增加渲染 latex 公式的功能。 ![Screenshot_2024-07-28-01-38-58-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/70243039/352769027-4ad162e9-325b-42a9-8c24-1e2b2025d59c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzQ1ODIsIm5iZiI6MTcyMjQzNDI4MiwicGF0aCI6Ii83MDI0MzAzOS8zNTI3NjkwMjctNGFkMTYyZTktMzI1Yi00MmE5LThjMjQtMWUyYjIwMjVkNTljLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOWMzYjlhMmQ3NTNiYjE4YTljZGVkY2RiM2RhYTJjMDgzNWFhNzBlZjg5YWE2MGU4NjBlNzUwMjNjYzdjMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUjX1w4mddB9J2mSOnlK-KxYYcVBdLtNzHmUHcZbGfU)

我在开发全新版本，预期有新的ui，我看看能不能把你这个渲染数学公式加进去，目前渲染markdown直接手写css渲染的，新版本看看能不能用现成的库渲染，最近比较忙，开发进度慢，目前已经重新调整了项目结构

**Comment by wuzheng228** [comment]
<img width="1540" alt="image" src="https://github.com/user-attachments/assets/0f24aebd-e7f4-499f-b756-9f1a6d2d3640">
现在支持公式渲染了，安装最新版

**Comment by iYnOtUo** [comment]
> <img alt="image" width="1540" src="https://private-user-images.githubusercontent.com/36781500/362144723-0f24aebd-e7f4-499f-b756-9f1a6d2d3640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzNTk3NjcsIm5iZiI6MTczOTM1OTQ2NywicGF0aCI6Ii8zNjc4MTUwMC8zNjIxNDQ3MjMtMGYyNGFlYmQtZTdmNC00OTlmLWI3NTYtOWYxYTZkMmQzNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEyVDExMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZTVlZmE3ZGE3YzVjZDk2MTNjOGZmZWU0NjFhZjY4OTZlYmVhY2VkOGM3OThlMDE0OTUxZmY1YmI5YTZlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FOLIx59kcfGf1PH2lDaCFabGodDR38D06MtVK4BTc1Y"> 现在支持公式渲染了，安装最新版

感谢感谢！！！平时喜欢写写文章，但是每次都要手动上传，受益了。
